//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carreteras.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BD_CARRETERASEntities : DbContext
    {
        public BD_CARRETERASEntities()
            : base("name=BD_CARRETERASEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_carreteras> tb_carreteras { get; set; }
        public virtual DbSet<tb_carreterasXciudades> tb_carreterasXciudades { get; set; }
        public virtual DbSet<tb_ciudades> tb_ciudades { get; set; }
        public virtual DbSet<tb_comunas> tb_comunas { get; set; }
        public virtual DbSet<tb_departamentos> tb_departamentos { get; set; }
        public virtual DbSet<tb_pantallas> tb_pantallas { get; set; }
        public virtual DbSet<tb_pantallasXroles> tb_pantallasXroles { get; set; }
        public virtual DbSet<tb_roles> tb_roles { get; set; }
        public virtual DbSet<tb_tramos> tb_tramos { get; set; }
        public virtual DbSet<tb_categorias> tb_categorias { get; set; }
        public virtual DbSet<tb_empleados> tb_empleados { get; set; }
        public virtual DbSet<tb_empleadosXusuarios> tb_empleadosXusuarios { get; set; }
        public virtual DbSet<tb_usuarios> tb_usuarios { get; set; }
        public virtual DbSet<tb_usuariosXroles> tb_usuariosXroles { get; set; }
    }
}
